"""add_role_to_users

Revision ID: 662ca0171997
Revises: e25df58897cb
Create Date: 2026-02-27 19:46:57.403151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662ca0171997'
down_revision: Union[str, None] = 'e25df58897cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) добавляем колонку как nullable
    op.add_column(
        "users",
        sa.Column("role", sa.String(length=50), nullable=True),
    )

    # 2) заполняем существующих пользователей дефолтом 'user'
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "UPDATE users SET role = 'user' WHERE role IS NULL"
        )
    )

    # 3) делаем колонку NOT NULL
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(length=50),
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
